package com.viartemev.thewhiterabbit.rpc

import com.viartemev.thewhiterabbit.queue.QueueSpecification

object RpcQueueSpecification : QueueSpecification(
    name = "", //the queue name will be generated by broker
    durable = false, //messages will not be persisted
    exclusive = true, //several consumers may not connect to this queue
    autoDelete = true //queue will be deleted once the client disconnects
)

